
server:
  shutdown: graceful
  
  
spring:
  jpa:
    show-sql: true
  docker:
    compose:
      start:
        arguments:
          - --pull=${PULL_POLICY:missing}
      stop:
        command: down
      skip:
        in-tests: false
      file:
        - ../docker-compose.yml

