spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: test
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initial-size: 5
      max-idle: 50 
      min-idle: 5
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 
      validation-query-timeout: 5000
      validation-interval: 30000
