
spring:
  data:
    redis:
      database: 11
      password: demo
      jedis:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 1
      sentinel:
        master: test
        password: demo
        nodes:
          - "${HOST_IP}:36379"
          - "${HOST_IP}:36381"
          - "${HOST_IP}:36381"
  docker:
    compose:
      file:
        - ../valkey/docker-compose.yml
      stop:
        command: down
      skip:
        in-tests: false