
spring:
  redis:
    redisson:
      file: classpath:redisson-valkey.yaml
  docker:
    compose:
      file:
        - ../valkey/docker-compose.yml
      stop:
        command: down
      skip:
        in-tests: false