server:
  servlet:
    session:
      timeout: 5m
  shutdown: graceful


spring:
  threads:
    virtual:
      enabled: true
  redis:
    redisson:
      file: classpath:redisson.yaml
  security:
    user:
      name: user
      password: password
  docker:
    compose:
      file:
        - ../docker-compose.yml
      start:
        arguments:
          - --pull=${PULL_POLICY:missing}
      stop:
        command: down
      skip:
        in-tests: false