
server:
  shutdown: graceful
  
  
spring:
  r2dbc:
    url: r2dbc:mariadb://127.0.0.1:3306/test
    username: test
    password: test
    pool:
      initial-size: 5
      max-size: 50
      max-idle-time: 60000
      validation-query: SELECT 1
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  docker:
    compose:
      start:
        arguments:
          - --pull=${PULL_POLICY:missing}
      stop:
        command: down
      skip:
        in-tests: false
      file:
        - ../docker-compose.yml

logging:
  level:
    org.springframework.graphql: debug
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
