server:
  shutdown: graceful

spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: demo
    password: demo
    virtual-host: /
  cloud:
    function:
      definition: ageAnalyze;ageCount
    stream:
      default-binder: rabbit
      bindings:
        new-user-out-0:
          destination: rb_new_user
          group: source
        ageAnalyze-in-0:
          destination: rb_new_user
          group: processor
        ageAnalyze-out-0:
          destination: rb_age_count
          group: processor
        ageCount-in-0:
          destination: rb_age_count
          group: processor
  docker:
    compose:
      stop:
        command: down
      skip:
        in-tests: false
