server:
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 5000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  docker:
    compose:
      skip:
        in-tests: false
      file:
        - ../docker-compose.yml
      start:
        arguments:
          - --pull=${PULL_POLICY:missing}
      stop:
        command: down