server:
  shutdown: graceful

spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/test
    username: test
    password: test
    pool:
      initial-size: 5
      max-size: 50
      max-idle-time: 60000
      validation-query: SELECT 1
  sql:
    init:
      mode: always
  docker:
    compose:
      skip:
        in-tests: false
      file:
        - ../docker-compose.yml
      start:
        arguments:
          - --pull=${PULL_POLICY:missing}
      stop:
        command: down
      
      
logging:
  level:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
