
server:
#  port: 0
  shutdown: graceful
  
  
spring:
  rsocket:
    server:
      port: 9191
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/test
    username: test
    password: rest
    pool:
      initial-size: 5
      max-size: 50
      max-idle-time: 60000
      validation-query: SELECT 1
  graphql:
    rsocket:
      mapping: graphql
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  docker:
    compose:
      stop:
        command: down
      skip:
        in-tests: false
      file: @basedir@/../docker-compose.yml
      
logging:
  level:
    org.springframework.graphql: debug
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
